//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HARO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gebrauchte
    {
        public int id { get; set; }
        public string Hersteller { get; set; }
        public string Bezeichnung { get; set; }
        public string Kategorie { get; set; }
        public string Antrieb { get; set; }
        public Nullable<int> Baujahr { get; set; }
        public Nullable<int> Betriebsstunden { get; set; }
        public Nullable<int> Bauhoehe { get; set; }
        public Nullable<int> Tragkraft { get; set; }
        public Nullable<int> Leergewicht { get; set; }
        public string LBH { get; set; }
        public string Mast { get; set; }
        public Nullable<int> AnzahlVentile { get; set; }
        public Nullable<int> MaxHubhoehe { get; set; }
        public string Preis { get; set; }
        public string Besonderheiten { get; set; }
        public string Beschreibung { get; set; }
    }
}
