//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HARO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontaktanfragen
    {
        public int id { get; set; }
        public string Firma { get; set; }
        public string Anpartner { get; set; }
        public string MailTel { get; set; }
        public string Thema { get; set; }
    }
}
