//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HARO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HaroEntities : DbContext
    {
        public HaroEntities()
            : base("name=HaroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BilderAnzeigen> BilderAnzeigen { get; set; }
        public virtual DbSet<Gebrauchte> Gebrauchte { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Kontaktanfragen> Kontaktanfragen { get; set; }
    }
}
